name: Matcha_LevelSystem
version: 1.0-SNAPSHOT
main: net.matcha.matcha_levelsystem.Matcha_LevelSystem
authors: [Ikirudo]
description: LevelSystem in MatchaServer
depend: [ActionBarAPI]
softdepend: [ActionBarAPI]
commands:
  levelset:
    description: 【LevelSystem】PlayerのLevel値を変更する。
    usage: /<command> [player] value
    permission: levelsystem.op
    permission-message: You do not have [<permission>]kengen.
  expset:
    description: 【LevelSystem】PlayerのExp値を変更する。
    usage: /<command> [player] value
    permission: levelsystem.op
    permission-message: You do not have [<permission>]kengen.
  levelreload:
    description: 【LevelSystem】LevelSystemPluginをリロードする。
    usage: /<command>
    permission: levelsystem.op
    permission-message: You do not have [<permission>]kengen.
  levelsave:
    description: 【LevelSystem】オンライン中のプレイヤーのLevelExpの変更をconfigにセーブする。
    usage: /<command>
    permission: levelsystem.op
    permission-message: You do not have [<permission>]kengen.
  setsp:
    description: set sp
    usage: /<command> [sp] <player>
    permission: levelsystem.op
    permission-message: You do not have [<permission>]kengen.
  resetsp:
    description: reset sp
    usage: /<command> <player>
    permission: levelsystem.op
    permission-message: You do not have [<permission>]kengen.
  sp:
    description: sp
    usage: /<command>
  stats:
    description: stats
    usage: /<command>
  status:
    description: statuss
    usage: /<command>
permissions:
  levelsystem.op:
    default: false
  levelsystem.notop:
    default: true
default-permission: levelsystem.notop