name: Matcha_LevelSystem
version: 1.0-SNAPSHOT
main: net.matcha.matcha_levelsystem.Matcha_LevelSystem
authors: [Ikirudo]
description: LevelSystem in MatchaServer
depend: [ActionBarAPI]
softdepend: [ActionBarAPI]