name: Matcha_Util
version: ${project.version}
main: net.matcha.matcha_util.Matcha_Util
api-version: 1.13
authors: [Ikirudo]
softdepend: [Matcha_ItemStack]
description: UtilityPlugin in MatchaServer
commands:
  ban:
    description: 【Matcha_Util】configにban情報を保存してbanする。
    usage: /<command> <player>
    permission: util.op
    permission-message: You do not have [<permission>].
  kick:
    description: 【Matcha_Util】configにkick情報を保存してkickする。
    usage: /<command> <player>
    permission: util.op
    permission-message: You do not have [<permission>].
  minecraft:ban:
    description: 【Matcha_Util】configにban情報を保存してbanする。
    usage: /<command> <player>
    permission: util.op
    permission-message: You do not have [<permission>].
  minecraft:kick:
    description: 【Matcha_Util】configにkick情報を保存してkickする。
    usage: /<command> <player>
    permission: util.op
    permission-message: You do not have [<permission>].
  bancheck:
    description: 【Matcha_Util】<player>のban情報を表示。
    usage: /<command> <player>
    permission: util.op
    permission-message: You do not have [<permission>].
  kickcheck:
    description: 【Matcha_Util】<player>のkick情報を表示。
    usage: /<command> <player>
    permission: util.op
    permission-message: You do not have [<permission>].
permissions:
  util.op:
    default: false
  util.notop:
    default: true
default-permission: util.notop